/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TabImport } from './routes/$tab'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TabRoute = TabImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$tab': {
      id: '/$tab'
      path: '/$tab'
      fullPath: '/$tab'
      preLoaderRoute: typeof TabImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tab': typeof TabRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tab': typeof TabRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$tab': typeof TabRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$tab'
  id: '__root__' | '/' | '/$tab'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabRoute: typeof TabRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabRoute: TabRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$tab"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$tab": {
      "filePath": "$tab.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
